make: main.cpp
	g++ main.cpp functions.cpp -o a1.07 -lm -lncurses
clean:
	rm -f a1.07
debug:
	g++ -g -o seg main.cpp functions.cpp -lncurses
run:
	gdb ./seg
split:	
	vim -O functions.cpp functions.h

